### PR TITLE
started to implement text

### PR DESCRIPTION
**Pull request by florent37**

### CODE REVIEW

**Comment by MohamedAmineB** [comment]
Hi, very great job, very exciting!
With this new "text" feature, do you also intend to add inputField ?

**Comment by florent37** [comment]
That depends what you expect from an input field, like the sample ?

**Comment by MohamedAmineB** [comment]
yep, like the sample, with some controls over hint, error, text style, counter text, ... in harmony with the design !
thx for your quick reply.

**Comment by florent37** [comment]
reworked and moved to feat/paragraph

**Pull request closed without merging**
