### PR TITLE
 change AnimatedScale Class to NeumorphicAnimatedScale to resolve conflict AnimatedScale class which have been reccently to flutter

### PR DESCRIPTION
**Pull request by alionour**
…filect with AnimatedScale class of flutter

### CODE REVIEW

**Comment by enigma-rdev** [comment]
Import is missing in the PR 
Add the  import 'animation/animated_scale.dart' ; to switch.dart file

**Comment by alionour** [comment]
> Import is missing in the PR
> Add the import 'animation/animated_scale.dart' ; to switch.dart file

It is already there .

**Comment by avi-yadav** [comment]
Can we get this merged? This is blocking me to move to flutter 2.5.

**Comment by miguelpruivo** [comment]
Dup of #240 which was already merged. Thank you!

**Pull request closed without merging**
