### PR TITLE
add app, app bar and back button

### LINKED ISSUE #122: Neumorphic AppBar
Currently if you try to use the material appBar and put neumorphic button on it it will be weird as the effect is cut by the size of the appBar. Would be nice to have a appBar specific to neumorphic that allow you to do:
Capture d’écran 2020-05-27 à 14 47 39
directly out of the box instead of doing it under Scaffold body manually

### PR DESCRIPTION
**Pull request by jaumard**
fix #122
I also removed `UsedTheme` to use the existing `ThemeMode`

### CODE REVIEW

**Comment by jaumard** [comment]
I have added a `defaultStyle` on the theme, the idea is to have a global one that you can merge/override later by providing a specific one. But it will need changes on all components that are currently using NeumorphicStyle, so I'll update those components on another PR to avoir a huge one. That will allow user to have less style to apply across their app. 

I also need to add the boxShape on the app bar fields for the button to use that one automatically if specify like we talk earlier, but same I'll do it in another PR. 

This one is good to me, let me know what you think

**Comment by jaumard** [comment]
I have removed `defaultStyle` because I finally understand that all field was already on the theme ^^ but not sure those theme fields are used on all components by default, or I didn't understand how it works that's possible

**Comment by florent37** [comment]
I see you're doing a lot of changed in this PR, I'll wait until you tell me to review before opening it :)

**Comment by jaumard** [comment]
Yes sorry for that :) I'll not touch it more except to fix your comments. So you can review it. 
For now buttons under appBar need manual tweak to look good (basically need to remove button's padding), I plan on fixing that on another PR later by providing an AppBarTheme or something to override the default style when inside an app bar.

**Comment by florent37** [comment]
Ok :) I start review it so ! do you have created a sample ?

**Comment by florent37** [comment]
yes : `main_home.dart`

**Comment by florent37** [comment]
I think the sample should stay in light mode, my computer is in dark mode & it's ugly here :) 

we'll add `themeMode: ThemeMode.light,` in the root app

then add   

```
 Scaffold(
        backgroundColor: NeumorphicTheme.baseColor(context),
```

into playground, because the scaffold background color is wierd

**Comment by florent37** [comment]
if the `appBar` uses `automaticallyImplyLeading` we should add a way to provide an argument of type `NeumorphicBoxShape` to have for example a circle back button, without defining entierely the leading widget

```
appBar: NeumorphicAppBar(
     title: "my app",
     leadingBoxShape: NeumorphicBoxShape.circle(),
     ...
```

for example (i'm not sure of the arg name)

**Comment by jaumard** [comment]
> we'll add themeMode: ThemeMode.light, in the root app 

Right I didn't test in dark mode ^^ 

>  Scaffold(
        backgroundColor: NeumorphicTheme.baseColor(context),

There is no need as it's what is done under NeumorphicApp already :) 

> if the appBar uses automaticallyImplyLeading we should add a way to provide an argument of type NeumorphicBoxShape to have for example a circle back button, without defining entierely the leading widget

Yeah that's the non finished part I was talking about, the idea here is to have a NeumorphicAppBarTheme where you can configure a `NeumorphicStyle` and a `shape` and the buttons will retrieve those automatically. But I'll do that in another PR if you don't mind because there is a lot going on here I'm getting a bit lost ^^

> Oh i forgot, thanks for this MR

No problem it was cool to do :)

**Comment by jaumard** [comment]
I have pushed `themeMode: ThemeMode.light,` in the root app. 

Do you need me to do anymore changes on this ?

**Comment by florent37** [comment]
Nope I try again & will merge this :)

**Comment by florent37** [comment]
I merge it :) If we have futher work we will do this on master or others PR

**Pull request merged**
