### PR TITLE
 optimization, curves, indicator animation, fixed switch disable animation

### PR DESCRIPTION
**Pull request by Overman775**
A little help to the project 😉

### CODE REVIEW

**Comment by florent37** [comment]
wow that look amazing ! 

Thanks I merge this, this will be part of 3.0.0

I don't know if you noticed but I added you as contributor in the readme :)

**Comment by florent37** [comment]
you rock :)

**Comment by Overman775** [comment]
@florent37 Thank you for adding to the list of contributors 🚀 
I plan litl fix appBar tomorrow(icons, sizes, etc.) 😉

**Comment by florent37** [comment]
I pushed the 3.0.0 tonight, but no worry, it'll be in 3.0.1 :D 

thanks a lot for you work

**Pull request merged**
