### PR TITLE
Resolved flutter 2.5 Conflict with `AnimatedScale`

### LINKED ISSUE #239: Conflict of AnimatedScale with Flutter 2.5.0
`Error: 'AnimatedScale' is imported from both 'package:flutter/src/widgets/implicit_animations.dart' and 'package:flutter_neumorphic/src/widget/animation/animated_scale.dart'`

After Flutter 2.5.0 release AnimatedScale is conflicting with flutter's implicit_animations.dart

Will create a PR to resolve it ASAP.

### PR DESCRIPTION
**Pull request by tsvillain**
will close #239

### CODE REVIEW

**Comment by sohan-scrobits** [comment]
My deadline for the project is this Friday. I don't know when this will get merged. Need this package lol.

**Comment by Amirnlz** [comment]
I use this solution, but it's not work for me.

**Comment by kartik1225** [comment]
> My deadline for the project is this Friday. I don't know when this will get merged. Need this package lol.

If you are still waiting then you can do the following in `pubspec.yaml`

```
flutter_neumorphic:
  git:
        url: https://github.com/tsvillain/Flutter-Neumorphic.git
```

**Review by miguelpruivo — APPROVED** [review]
LGTM.

**Pull request merged**
